import { useState } from "react";
const SCENARIOS = {
conservative: { label: "Vorsichtig", color: "#6B7280", mix: { assistant: 75, friend: 20, partner: 5 }, topupRate: 18, topupAvg: 10, arpu: 21.95, contribution: 15.86, margin: 72.2, years: [{ y: 1, users: 120, revenue: 31608, cb: 22833, fix: 21600, profit: 1233 },{ y: 2, users: 300, revenue: 79020, cb: 57096, fix: 36000, profit: 21096 },{ y: 3, users: 500, revenue: 131700, cb: 95136, fix: 54000, profit: 41136 },{ y: 4, users: 900, revenue: 237060, cb: 171245, fix: 84000, profit: 87245 },{ y: 5, users: 1400, revenue: 368760, cb: 266381, fix: 120000, profit: 146381 }] },
realistic: { label: "Realistisch", color: "#3B82F6", mix: { assistant: 65, friend: 25, partner: 10 }, topupRate: 22, topupAvg: 10, arpu: 25.35, contribution: 18.20, margin: 71.8, years: [{ y: 1, users: 250, revenue: 76050, cb: 54596, fix: 26400, profit: 28196 },{ y: 2, users: 700, revenue: 212940, cb: 152890, fix: 48000, profit: 104890 },{ y: 3, users: 1400, revenue: 425880, cb: 305735, fix: 78000, profit: 227735 },{ y: 4, users: 2800, revenue: 851760, cb: 611470, fix: 144000, profit: 467470 },{ y: 5, users: 4200, revenue: 1277640, cb: 917204, fix: 216000, profit: 701204 }] },
strong: { label: "Stark", color: "#10B981", mix: { assistant: 50, friend: 32, partner: 18 }, topupRate: 28, topupAvg: 12, arpu: 31.16, contribution: 22.21, margin: 71.3, years: [{ y: 1, users: 500, revenue: 186960, cb: 133255, fix: 36000, profit: 97255 },{ y: 2, users: 1500, revenue: 560880, cb: 399766, fix: 72000, profit: 327766 },{ y: 3, users: 3000, revenue: 1121760, cb: 799531, fix: 120000, profit: 679531 },{ y: 4, users: 5500, revenue: 2056560, cb: 1465807, fix: 228000, profit: 1237807 },{ y: 5, users: 9000, revenue: 3365280, cb: 2398594, fix: 360000, profit: 2038594 }] }
};
const TIERS = [
  { name: "Free", price: "€0", priceNum: 0, color: "#94A3B8", voiceCost: 0, cb: 0, desc: "Kennenlernen", features: ["Chat + Voice (limitiert)", "Erstes Gespräch", "Einfache Zusammenfassung"] },
  { name: "Assistant", price: "€14.90", priceNum: 14.90, color: "#6366F1", voiceCost: 4.07, cb: 10.83, desc: "Klarheit & Nutzen", features: ["Chat & Voice", "Session Summaries", "Brainstorming & Ideen", "Meeting-Vorbereitung", "Sales Pitch Übung"] },
  { name: "Friend", price: "€29.90", priceNum: 29.90, color: "#8B5CF6", voiceCost: 7.90, cb: 22.00, desc: "Persönlich & Kontinuierlich", features: ["Alles aus Assistant", "Persönlichere Sophie", "Stärkere Kontinuität", "Zugang zu vergangenen Sessions", "Tieferes Kontextverständnis"] },
  { name: "Partner", price: "€59.90", priceNum: 59.90, color: "#A855F7", voiceCost: 19.15, cb: 40.75, desc: "Tiefste Bindung", features: ["Alles aus Friend", "Stärkste Kontinuität", "Priority Access", "Meeting Mode", "Early Access Features"] },
];
const SPRINT_STATUS = { overall: 85, packages: [
  { name: "Voice-Hauptflow stabilisieren", progress: 90, status: "Fast fertig", statusColor: "#22C55E", details: "OpenAI Realtime voll integriert. Retry (3 Attempts + Backoff), VAD, Session-Lock, Soft-End-Warning. Offen: mobile Safari Edge Cases." },
  { name: "Auth / Magic Link sauber", progress: 95, status: "Fertig", statusColor: "#10B981", details: "PKCE Callback, Bearer-Token in allen Endpoints, Login + Callback Pages komplett." },
  { name: "Realtime-Session-Fehler beseitigen", progress: 85, status: "Fast fertig", statusColor: "#22C55E", details: "acquire_realtime_lock() mit TTL, 429/402 Error-Codes, Daily Free Cap, Retry-Logik. Offen: Session-Timeout UX mobile." },
  { name: "Session-Ende + Insights", progress: 95, status: "Fertig", statusColor: "#10B981", details: "Backend: structured JSON via Claude API -> conversation_outputs. Frontend: Panel mit Summary/Insights/Next Steps + Transcript." },
  { name: "Memory Chat<->Voice konsistent", progress: 75, status: "In Arbeit", statusColor: "#F59E0B", details: "Text-Chat existiert, Voice-Offer Mechanismus, x-sophie-handover, shared user_profile/user_relationship. sophie-core.js noch Stub." },
], nextSteps: [
  { prio: "Kritisch", task: "Fremden Tester durchschicken", desc: "Done-Kriterium Sprint 1. Reconnect, Audio-Permissions, Browser-Kompatibilität.", status: "Offen" },
  { prio: "Kritisch", task: "Mobile Safari + langsame Verbindungen", desc: "WebSocket-Reconnect, Audio-Permissions, Timeout-UX mobile.", status: "Offen" },
  { prio: "Hoch", task: "sophie-core.js implementieren", desc: "Prompt-Building extrahieren. Aktuell inline + TODO.", status: "Offen" },
  { prio: "Hoch", task: "Stripe 4-Tier vorbereiten", desc: "starter/plus -> free/assistant/friend/partner -> Sprint 2.", status: "Sprint 2" },
  { prio: "Mittel", task: "Insights-Panel Polish", desc: "Panel existiert. Feinschliff Layout und Animationen.", status: "Offen" },
], codebaseStats: { apiEndpoints: 9, dbTables: "8+", currentBranch: "fix/memory-short-long-term", stripeModel: "2-Tier -> 4-Tier geplant Sprint 2" } };
const WEBAPP = { must: [
  { id: 1, title: "Chat + Voice = eine Sophie", desc: "Kein Bruch. Gleiche Persona, gleicher Kontext, gleiche Memory. Wenn der User im Chat seinen Namen sagt, darf Voice nicht erneut fragen.", icon: "🧠", status: "in_progress" },
  { id: 2, title: "Mobile UX kompromisslos", desc: "iPhone als Hauptreferenz. Große Touch-Zonen, Safe Areas, kein springendes Layout. Voice-Button dominiert. Keyboard darf nichts kaputtmachen.", icon: "📱", status: "in_progress" },
  { id: 3, title: "Reentry brutal sauber", desc: "Nach Magic Link kein Chaos. Rückkehr zu /talk stabil. Offene Session erkennbar. Keine Redirect-Ketten, keine UI-Sackgassen.", icon: "🔄", status: "partial" },
  { id: 4, title: "Voice-Start glasklar & robust", desc: "Eindeutige Zustände: bereit / hört zu / verbindet / spricht / beendet. Kein Hängenbleiben. Visuelles Feedback beim Listening.", icon: "🎙️", status: "mostly_done" },
  { id: 5, title: "Trial & Paywall natürlich", desc: "Session-Ende weich auffangen. Insights zeigen. Upgrade als logische Fortsetzung, nicht als Blockade. Kein Stress durch Timer.", icon: "💳", status: "partial" },
  { id: 6, title: "Auth zerstört nie die Illusion", desc: "Login erst wenn sinnvoll. Nach Auth direkt zurück in die Experience. Kein Gefühl von 'raus aus Sophie, rein in Technik'.", icon: "🔐", status: "mostly_done" },
  { id: 7, title: "Tracking als Steuerzentrale", desc: "landing_view -> start_voice -> auth -> paywall -> checkout -> return_visit. Nach Sprache, Device, Source, Trial vs Paid.", icon: "📊", status: "partial" },
  { id: 8, title: "Installierbarkeit sauber", desc: "Web App Manifest, Icons, Splash. Sophie als Home Screen Icon = psychologischer Shift von 'Seite' zu 'Begleiter'.", icon: "⬇️", status: "todo" },
  { id: 9, title: "Performance: gefühlt sofort", desc: "Landing und /talk schnell. Keine schweren Assets im kritischen Pfad. State nicht verlieren. Ladezustände elegant.", icon: "⚡", status: "partial" },
  { id: 10, title: "Ein klarer Core-Use-Case", desc: "Denken klären, Entscheidungen sortieren, reflektieren. Nicht 7 Modi gleichzeitig. Fokus schlägt Feature-Breite.", icon: "🎯", status: "done" },
], should: [
  { id: 1, title: "Install-Hinweis intelligent", desc: "Nicht sofort. Erst nach positiver Erfahrung. 'Keep Sophie close' statt technischer Text." },
  { id: 2, title: "Return-to-Sophie Moment", desc: "Wiederkehr wie Fortsetzung, nicht wie Neustart. Subtiler personalisierter Wiedereinstieg." },
  { id: 3, title: "Session-Ende als Produktmoment", desc: "Summary, Key Insights, Action Points. Klarer nächster Schritt. 'Weiter im Chat' oder 'später fortsetzen'." },
  { id: 4, title: "Chat - Voice enger verzahnt", desc: "Wechsel ohne mentalen Neustart. Chat bereitet Voice vor. Voice setzt Chat fort." },
  { id: 5, title: "Klare UI-States", desc: "idle / ready / connecting / listening / speaking / reconnecting / ended / paywall — jeder State klar." },
  { id: 6, title: "Sprachumschaltung 100%", desc: "Landing, Chat, Voice, Buttons, Paywall, Summary — überall dieselbe Sprache." },
  { id: 7, title: "Vertrauensschicht", desc: "Datenschutz UX-seitig integriert. Vertrauen über Stabilität und Klarheit." },
  { id: 8, title: "Funnel je Quelle", desc: "Organisch vs. Paid vs. Social — je Quelle andere Erwartung und Einstieg." },
  { id: 9, title: "Payment-Varianten testbar", desc: "Monatsabo, Top-up, Einstiegsangebot. Pricing wird nicht auf Anhieb perfekt." },
  { id: 10, title: "App-Gefühl visuell", desc: "Icon, Motion, Übergänge. Ruhig, hochwertig, nicht techy." },
], later: [
  { title: "Native App", reason: "Erst wenn Retention da, Funnel stabil, Core klar." },
  { title: "Push-Strategie", reason: "Companion-Push kann schnell nerven oder creepy wirken." },
  { title: "Fortgeschrittene Personalisierung", reason: "Adaptive Opener, feinere Rückbezüge. Erst wenn Basis stabil." },
  { title: "Mehr Modi (Sales Coach, Think Tank...)", reason: "Erst muss der Grundkern gewinnen." },
  { title: "Community / Sharing / viral", reason: "Aktuell nicht der Engpass." },
  { title: "Aufwendige visuelle Spielereien", reason: "Nur wenn Performance und Fokus nicht leiden." },
], blocks: [
  { name: "Core Experience", color: "#EF4444", items: ["Chat/Voice/Memory identisch", "Reentry stabil", "Voice-Start robust", "Mobile States sauber"] },
  { name: "Conversion", color: "#F97316", items: ["Trial-Ende natürlich", "Upgrade-Fluss sauber", "Auth ohne Bruch", "Paywall als Fortsetzung"] },
  { name: "App-Feeling", color: "#A855F7", items: ["Installierbarkeit", "Return-Momente", "App-artiges Produktgefühl", "Kein Browser-Gefühl"] },
  { name: "Steuerbarkeit", color: "#3B82F6", items: ["Event-Tracking komplett", "Funnel-Sicht", "Pricing-Tests", "Retention-Messung"] },
] };
const SPRINTS = [
  { id: 1, name: "Produktkern", weeks: "W1-W3", prio: "P0", color: "#EF4444", progress: 85, packages: SPRINT_STATUS.packages.map(p => `${p.name} (${p.progress}%)`), deps: "-", done: "Fremder Tester kommt ohne Hilfe durch", doneReached: false, notes: "Backend stark, Frontend Voice-UI + Insights komplett. Blocker: externer Nutzertest." },
  { id: 2, name: "Monetarisierung", weeks: "W4-W6", prio: "P0", color: "#F97316", progress: 25, packages: ["4-Tier Migration: starter/plus -> free/assistant/friend/partner", "Stripe Checkout (3 Sub-Preise + 3 Top-ups)", "includedSecondsForPlan() auf 4 Tiers", "Usage-Tracking & Limits pro Tier", "Legal + Checkboxen"], deps: "Sprint 1", done: "User kann kaufen + nutzen ohne Support", doneReached: false, notes: "Stripe bereits für 2 Tiers. Migration auf 4 ist Hauptarbeit." },
  { id: 3, name: "Conversion", weeks: "W7-W9", prio: "P1", color: "#EAB308", progress: 10, packages: ["Landing Page Pricing-Cards", "Onboarding/Erstgespräch optimieren", "Upgrade-Momente einbauen", "Post-Session Insights stärken"], deps: "Sprint 2", done: "User versteht Produkt + Nutzen sofort", doneReached: false, notes: "Landing existiert. Onboarding + Upgrade-Nudges fehlen." },
  { id: 4, name: "Retention", weeks: "W10-W12", prio: "P1", color: "#22C55E", progress: 5, packages: ["Relationship Layer implementieren", "Chat als Ergänzung", "History/vergangene Insights", "Behavior Sliders System", "Memory-Scope je Tier"], deps: "Sprint 3", done: "Plausiblen Grund wiederzukommen", doneReached: false, notes: "Memory-Grundstruktur existiert. Behavior Sliders + Tier-Scope fehlen." },
  { id: 5, name: "Wachstum", weeks: "W13-W16", prio: "P2", color: "#3B82F6", progress: 0, packages: ["Social Hooks / Sophie Says", "Content / Shorts / Ads", "Funnel-Tracking", "Conversion-Messung", "Pricing-Experimente"], deps: "Sprint 4", done: "Traffic -> User -> Zahler Pipeline steht", doneReached: false, notes: "Noch nicht gestartet." },
];
const ARCH_LAYERS = [
  { name: "Identity Layer", desc: "Unveränderliche Kernpersona", color: "#8B5CF6", details: "Warm, intelligent, aufmerksam, natürlich. Ändert sich nie." },
  { name: "Relationship Layer", desc: "Beziehungstiefe je Tier", color: "#A855F7", details: "Free -> Assistant -> Friend -> Partner. Steuert Nähe, Initiative, Erinnerungstiefe." },
  { name: "Behavior Layer", desc: "Dynamische Verhaltenswerte", color: "#C084FC", details: "warmth, structure, reflection, assertiveness, energy, playfulness — pro Turn." },
  { name: "Memory & Permission", desc: "Kontext- & Datengrenzen", color: "#DDD6FE", details: "Was gespeichert wird, wie tief, wie lange. Beziehungsgefühl vs. Creepiness-Grenze." },
];
function fmt(n) { return n >= 1e6 ? `€${(n/1e6).toFixed(1)}M` : n >= 1e3 ? `€${(n/1e3).toFixed(0)}k` : `€${n}`; }
function BarChart({data,dataKey,color}){const max=Math.max(...data.map(d=>d[dataKey]));return(<div style={{display:"flex",alignItems:"flex-end",gap:8,height:160,padding:"0 4px"}}>{data.map((d,i)=>{const h=max>0?(d[dataKey]/max)*140:0;return(<div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><span style={{fontSize:10,color:"#9CA3AF",fontWeight:600}}>{fmt(d[dataKey])}</span><div style={{width:"100%",height:h,background:`linear-gradient(180deg,${color},${color}88)`,borderRadius:"6px 6px 2px 2px",minHeight:2,transition:"height 0.5s ease"}}/><span style={{fontSize:11,color:"#6B7280",fontWeight:500}}>J{d.y}</span></div>);})}</div>);}
function ProgressBar({progress,color,height=8}){return(<div style={{width:"100%",height,background:"#2A2D37",borderRadius:height/2,overflow:"hidden"}}><div style={{width:`${progress}%`,height:"100%",background:`linear-gradient(90deg,${color},${color}CC)`,borderRadius:height/2,transition:"width 0.8s ease"}}/></div>);}
function MiniStat({label,value,sub,accent}){return(<div style={{textAlign:"center",padding:"12px 8px"}}><div style={{fontSize:11,color:"#9CA3AF",fontWeight:500,textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:4}}>{label}</div><div style={{fontSize:22,fontWeight:700,color:accent||"#F9FAFB"}}>{value}</div>{sub&&<div style={{fontSize:11,color:"#6B7280",marginTop:2}}>{sub}</div>}</div>);}
const si=s=>s==="done"?"✓":s==="mostly_done"?"◉":s==="in_progress"?"◐":s==="partial"?"◔":"○";
const sc2=s=>s==="done"?"#10B981":s==="mostly_done"?"#22C55E":s==="in_progress"?"#F59E0B":s==="partial"?"#F97316":"#6B7280";
const sl=s=>s==="done"?"Fertig":s==="mostly_done"?"Fast fertig":s==="in_progress"?"In Arbeit":s==="partial"?"Teilweise":"Offen";
export default function SophieBusinessPlan(){
const[activeScenario,setActiveScenario]=useState("realistic");
const[activeTab,setActiveTab]=useState("overview");
const[expandedSprint,setExpandedSprint]=useState(null);
const[expandedLayer,setExpandedLayer]=useState(null);
const[wv,setWv]=useState("must");
const sc=SCENARIOS[activeScenario];const y5=sc.years[4];
const tabs=[{id:"overview",label:"Übersicht"},{id:"webapp",label:"📱 Web-App"},{id:"sprint",label:"Sprint Status"},{id:"pricing",label:"Pricing"},{id:"finance",label:"Finanzen"},{id:"architecture",label:"Architektur"},{id:"project",label:"Projektplan"},{id:"why",label:"Warum Sophie?"}];
return(
<div style={{fontFamily:"'DM Sans','Manrope',system-ui,sans-serif",background:"#0F1117",color:"#E5E7EB",minHeight:"100vh",padding:"24px 16px"}}>
<style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,500;0,9..40,700;1,9..40,400&family=JetBrains+Mono:wght@400;600&display=swap');*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:#374151;border-radius:3px}`}</style>
<div style={{maxWidth:960,margin:"0 auto 32px",textAlign:"center"}}>
<div style={{fontSize:11,fontWeight:500,color:"#A855F7",letterSpacing:"0.15em",textTransform:"uppercase",marginBottom:8}}>Business Plan 2026–2031</div>
<h1 style={{fontSize:32,fontWeight:700,color:"#F9FAFB",lineHeight:1.2,marginBottom:8}}>Meet Sophie</h1>
<p style={{fontSize:14,color:"#9CA3AF",maxWidth:520,margin:"0 auto"}}>Premium Voice-AI Relationship Subscription — Geschäftsmodell, Pricing, Architektur & Roadmap</p>
</div>
<div style={{maxWidth:960,margin:"0 auto 24px",display:"flex",gap:3,flexWrap:"wrap",background:"#1A1D27",borderRadius:12,padding:4}}>
{tabs.map(t=>(<button key={t.id} onClick={()=>setActiveTab(t.id)} style={{flex:1,minWidth:72,padding:"10px 6px",borderRadius:8,border:"none",cursor:"pointer",background:activeTab===t.id?(t.id==="webapp"?"#F97316":"#A855F7"):"transparent",color:activeTab===t.id?"#FFF":"#9CA3AF",fontSize:11,fontWeight:600,fontFamily:"inherit",transition:"all 0.2s"}}>{t.label}</button>))}
</div>
<div style={{maxWidth:960,margin:"0 auto"}}>
{activeTab==="overview"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{display:"flex",gap:8}}>{Object.entries(SCENARIOS).map(([k,v])=>(<button key={k} onClick={()=>setActiveScenario(k)} style={{flex:1,padding:"14px 12px",borderRadius:10,border:activeScenario===k?`2px solid ${v.color}`:"2px solid #2A2D37",background:activeScenario===k?`${v.color}15`:"#1A1D27",cursor:"pointer",color:activeScenario===k?v.color:"#9CA3AF",fontSize:13,fontWeight:600,fontFamily:"inherit"}}>{v.label}</button>))}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[{l:"ARPU/Mo",v:`€${sc.arpu}`,a:sc.color},{l:"DB-Marge",v:`${sc.margin}%`,a:"#10B981"},{l:"Umsatz J5",v:fmt(y5.revenue),a:"#F59E0B"},{l:"Gewinn J5",v:fmt(y5.profit),a:"#A855F7",s:"vor Steuern"}].map((m,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,border:"1px solid #2A2D37"}}><MiniStat label={m.l} value={m.v} accent={m.a} sub={m.s}/></div>))}</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>UMSATZ / JAHR</div><BarChart data={sc.years} dataKey="revenue" color={sc.color}/></div><div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>OPERATIVER GEWINN / JAHR</div><BarChart data={sc.years} dataKey="profit" color="#10B981"/></div></div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37",overflowX:"auto"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>DETAILANSICHT — {sc.label.toUpperCase()}</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{color:"#6B7280",fontSize:11,textTransform:"uppercase"}}>{["Jahr","Paid User","Umsatz","DB","Fix","Gewinn"].map((h,i)=><th key={i} style={{padding:"8px 12px",textAlign:i===0?"left":"right"}}>{h}</th>)}</tr></thead><tbody>{sc.years.map((r,i)=>(<tr key={i} style={{borderTop:"1px solid #2A2D37"}}><td style={{padding:"10px 12px",fontWeight:600}}>Jahr {r.y}</td><td style={{padding:"10px 12px",textAlign:"right",fontFamily:"'JetBrains Mono',monospace"}}>{r.users.toLocaleString()}</td><td style={{padding:"10px 12px",textAlign:"right",fontFamily:"'JetBrains Mono',monospace",color:sc.color}}>{fmt(r.revenue)}</td><td style={{padding:"10px 12px",textAlign:"right",fontFamily:"'JetBrains Mono',monospace"}}>{fmt(r.cb)}</td><td style={{padding:"10px 12px",textAlign:"right",fontFamily:"'JetBrains Mono',monospace",color:"#EF4444"}}>{fmt(r.fix)}</td><td style={{padding:"10px 12px",textAlign:"right",fontFamily:"'JetBrains Mono',monospace",color:r.profit>0?"#10B981":"#EF4444",fontWeight:600}}>{fmt(r.profit)}</td></tr>))}</tbody></table></div>
</div>)}
{activeTab==="webapp"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{background:"linear-gradient(135deg,#1A1D27,#2A1A10)",borderRadius:14,padding:24,border:"1px solid #F9731640"}}>
<div style={{display:"flex",alignItems:"center",gap:14,marginBottom:12}}>
<div style={{width:48,height:48,borderRadius:12,background:"#F9731625",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}}>📱</div>
<div><div style={{fontSize:18,fontWeight:700,color:"#F9FAFB"}}>Mobile Web-App Richtlinie</div><div style={{fontSize:12,color:"#F97316"}}>100% Fokus: Browserbasierte Companion-App — keine klassische Website</div></div>
</div>
<div style={{fontSize:13,color:"#D1D5DB",lineHeight:1.7}}>Sophie ist kein Tool mit Chatfunktion. Sophie ist eine <strong style={{color:"#F9FAFB"}}>App-Erfahrung im Browser</strong>. Der User öffnet Sophie und ist direkt in seiner Welt — Home Screen statt Bookmark, Session-Fortsetzung statt Neustart. <strong style={{color:"#F97316"}}>Mobile ist das Hauptprodukt. Desktop ist Bonus.</strong></div>
</div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}>
<div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:12,textTransform:"uppercase",letterSpacing:"0.05em"}}>7 Leitprinzipien</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:6}}>
{[{w:"Installierbar",c:"#A855F7",s:"Home Screen = Begleiter"},{w:"Mobil perfekt",c:"#F97316",s:"iPhone als Referenz"},{w:"Schnell",c:"#EAB308",s:"Speed = Vertrauen"},{w:"Intim",c:"#EC4899",s:"Person, nicht System"},{w:"Reibungsarm",c:"#10B981",s:"Jede Reibung kostet"},{w:"Eigenes Payment",c:"#3B82F6",s:"Kein Store-Korsett"},{w:"Messbar",c:"#8B5CF6",s:"Funnel als Steuerpult"}].map((p,i)=>(<div key={i} style={{textAlign:"center",padding:"12px 4px",background:`${p.c}10`,borderRadius:10,border:`1px solid ${p.c}25`}}><div style={{fontSize:11,fontWeight:700,color:p.c,marginBottom:4}}>{p.w}</div><div style={{fontSize:9,color:"#9CA3AF",lineHeight:1.3}}>{p.s}</div></div>))}
</div>
</div>
<div style={{display:"flex",gap:6}}>
{[{id:"must",label:"Must Have",n:10,c:"#EF4444"},{id:"should",label:"Should Have",n:10,c:"#F59E0B"},{id:"later",label:"Later",n:6,c:"#6B7280"},{id:"blocks",label:"Umsetzung",n:4,c:"#A855F7"}].map(s=>(<button key={s.id} onClick={()=>setWv(s.id)} style={{flex:1,padding:"10px 8px",borderRadius:8,border:wv===s.id?`2px solid ${s.c}`:"2px solid #2A2D37",background:wv===s.id?`${s.c}15`:"#1A1D27",cursor:"pointer",color:wv===s.id?s.c:"#9CA3AF",fontSize:11,fontWeight:600,fontFamily:"inherit"}}>{s.label} ({s.n})</button>))}
</div>
{wv==="must"&&(<div style={{display:"flex",flexDirection:"column",gap:10}}>
<div style={{fontSize:11,color:"#EF4444",fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"}}>Ohne diese Punkte baut Sophie auf wackligem Fundament</div>
{WEBAPP.must.map((item,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37",display:"flex",gap:14,alignItems:"flex-start"}}><div style={{width:40,height:40,borderRadius:10,background:"#0F1117",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0}}>{item.icon}</div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{fontSize:14,fontWeight:600,color:"#F9FAFB"}}>{item.id}. {item.title}</span><span style={{fontSize:10,fontWeight:600,color:sc2(item.status),background:`${sc2(item.status)}20`,padding:"2px 8px",borderRadius:8}}>{si(item.status)} {sl(item.status)}</span></div><div style={{fontSize:12,color:"#9CA3AF",lineHeight:1.5}}>{item.desc}</div></div></div>))}
<div style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37"}}><div style={{display:"flex",gap:16,justifyContent:"center"}}>
{["done","mostly_done","in_progress","partial","todo"].map(s=>{const c=WEBAPP.must.filter(m=>m.status===s).length;return c>0?(<div key={s} style={{display:"flex",alignItems:"center",gap:6,fontSize:12}}><span style={{color:sc2(s),fontWeight:700}}>{si(s)}</span><span style={{color:"#9CA3AF"}}>{sl(s)}: {c}</span></div>):null;})}
</div></div>
</div>)}
{wv==="should"&&(<div style={{display:"flex",flexDirection:"column",gap:10}}>
<div style={{fontSize:11,color:"#F59E0B",fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"}}>Spürbar mehr Qualität — aber nicht der erste Engpass</div>
{WEBAPP.should.map((item,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37"}}><div style={{fontSize:13,fontWeight:600,color:"#F9FAFB",marginBottom:4}}>{item.id}. {item.title}</div><div style={{fontSize:12,color:"#9CA3AF",lineHeight:1.5}}>{item.desc}</div></div>))}
</div>)}
{wv==="later"&&(<div style={{display:"flex",flexDirection:"column",gap:10}}>
<div style={{fontSize:11,color:"#6B7280",fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"}}>Nett, wertvoll, aber jetzt noch nicht der Hebel</div>
{WEBAPP.later.map((item,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:14,border:"1px solid #2A2D37",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:13,fontWeight:600,color:"#D1D5DB"}}>{item.title}</div><div style={{fontSize:11,color:"#6B7280",textAlign:"right",maxWidth:300}}>{item.reason}</div></div>))}
</div>)}
{wv==="blocks"&&(<div style={{display:"flex",flexDirection:"column",gap:16}}>
<div style={{fontSize:11,color:"#A855F7",fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"}}>Operative Reihenfolge — Block 1 zuerst</div>
{WEBAPP.blocks.map((block,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:20,border:`1px solid ${block.color}30`}}>
<div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{width:32,height:32,borderRadius:8,background:`${block.color}25`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:700,color:block.color}}>{i+1}</div><div style={{fontSize:15,fontWeight:700,color:"#F9FAFB"}}>Block {i+1}: {block.name}</div></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{block.items.map((item,j)=>(<div key={j} style={{fontSize:12,color:"#D1D5DB",padding:"8px 12px",background:"#0F111788",borderRadius:8,borderLeft:`3px solid ${block.color}`}}>{item}</div>))}</div>
</div>))}
<div style={{background:"linear-gradient(135deg,#1A1D27,#1A0F0F)",borderRadius:14,padding:20,border:"1px solid #EF444440",textAlign:"center"}}>
<div style={{fontSize:14,fontWeight:700,color:"#F9FAFB",marginBottom:8}}>Größtes Risiko</div>
<div style={{fontSize:13,color:"#D1D5DB",lineHeight:1.6}}>Nicht: „Wir haben noch keine native App."<br/>Sondern: <strong style={{color:"#EF4444"}}>Das Produkt wirkt in wichtigen Momenten noch wie Technik statt wie Sophie.</strong></div>
</div>
</div>)}
</div>)}
{activeTab==="sprint"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",textTransform:"uppercase"}}>Sprint 1 — Produktkern (W1–W3)</div><div style={{fontSize:11,color:"#6B7280",marginTop:4}}>Done: Fremder Tester ohne Hilfe — <span style={{color:"#F59E0B"}}>Noch nicht erreicht</span></div></div><div style={{fontSize:28,fontWeight:700,color:"#A855F7"}}>{SPRINT_STATUS.overall}%</div></div><ProgressBar progress={SPRINT_STATUS.overall} color="#A855F7" height={10}/></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[{l:"Sprint 1",v:`~${SPRINT_STATUS.overall}%`,s:"Produktkern",a:"#A855F7"},{l:"Zeitplan",v:"W3/3",s:"Ende diese Woche",a:"#F59E0B"},{l:"API-Endpoints",v:SPRINT_STATUS.codebaseStats.apiEndpoints,s:"Live auf Vercel",a:"#3B82F6"},{l:"DB-Tabellen",v:SPRINT_STATUS.codebaseStats.dbTables,s:"RLS aktiv",a:"#10B981"}].map((m,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,border:"1px solid #2A2D37"}}><MiniStat label={m.l} value={m.v} sub={m.s} accent={m.a}/></div>))}</div>
<div style={{display:"flex",flexDirection:"column",gap:10}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",textTransform:"uppercase"}}>Arbeitspakete</div>{SPRINT_STATUS.packages.map((pkg,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div style={{fontSize:14,fontWeight:600,color:"#F9FAFB"}}>{i+1}. {pkg.name}</div><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:11,fontWeight:600,color:pkg.statusColor,background:`${pkg.statusColor}20`,padding:"3px 10px",borderRadius:10}}>{pkg.status}</span><span style={{fontSize:16,fontWeight:700,color:pkg.statusColor}}>{pkg.progress}%</span></div></div><ProgressBar progress={pkg.progress} color={pkg.statusColor}/><div style={{fontSize:12,color:"#9CA3AF",marginTop:8,lineHeight:1.5}}>{pkg.details}</div></div>))}</div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16,textTransform:"uppercase"}}>Nächste Schritte — KW13</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{SPRINT_STATUS.nextSteps.map((step,i)=>{const pc=step.prio==="Kritisch"?"#EF4444":step.prio==="Hoch"?"#F59E0B":"#3B82F6";return(<div key={i} style={{display:"flex",gap:12,padding:"12px 14px",background:"#0F111788",borderRadius:10}}><span style={{fontSize:14,fontWeight:700,color:"#6B7280",minWidth:28,textAlign:"center"}}>{i+1}</span><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{fontSize:13,fontWeight:600,color:"#F9FAFB"}}>{step.task}</span><span style={{fontSize:10,fontWeight:600,color:pc,background:`${pc}20`,padding:"2px 8px",borderRadius:8}}>{step.prio}</span></div><div style={{fontSize:12,color:"#9CA3AF"}}>{step.desc}</div></div><div style={{fontSize:11,color:step.status==="Offen"?"#F59E0B":"#6B7280",fontWeight:500,whiteSpace:"nowrap"}}>{step.status}</div></div>);})}</div></div>
<div style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37",fontSize:11,color:"#6B7280"}}>Stand: 24. März 2026 · Branch: <span style={{color:"#A855F7",fontFamily:"'JetBrains Mono',monospace"}}>{SPRINT_STATUS.codebaseStats.currentBranch}</span> · Stripe: {SPRINT_STATUS.codebaseStats.stripeModel}</div>
</div>)}
{activeTab==="pricing"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{TIERS.map((t,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:14,padding:20,border:i===3?`2px solid ${t.color}`:"1px solid #2A2D37",display:"flex",flexDirection:"column",gap:12,position:"relative",boxShadow:i===3?`0 0 30px ${t.color}20`:"none"}}>{i===3&&<div style={{position:"absolute",top:-10,right:16,background:t.color,color:"#FFF",fontSize:10,fontWeight:700,padding:"3px 10px",borderRadius:20}}>PREMIUM</div>}<div style={{fontSize:11,color:t.color,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.1em"}}>{t.name}</div><div style={{fontSize:24,fontWeight:700,color:"#F9FAFB"}}>{t.price}<span style={{fontSize:12,color:"#6B7280",fontWeight:400}}>{t.priceNum>0?" /mo":""}</span></div><div style={{fontSize:12,color:"#9CA3AF"}}>{t.desc}</div><div style={{borderTop:"1px solid #2A2D37",paddingTop:12,display:"flex",flexDirection:"column",gap:6}}>{t.features.map((f,j)=>(<div key={j} style={{fontSize:11,color:"#D1D5DB",display:"flex",gap:6}}><span style={{color:t.color,fontSize:14,lineHeight:1}}>✓</span><span>{f}</span></div>))}</div></div>))}</div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>UNIT ECONOMICS PRO PAID USER / MONAT</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{TIERS.filter(t=>t.priceNum>0).map((t,i)=>{const pct=(t.cb/t.priceNum)*100;return(<div key={i} style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:80,fontSize:12,fontWeight:600,color:t.color}}>{t.name}</div><div style={{flex:1,height:28,background:"#2A2D37",borderRadius:6,overflow:"hidden",position:"relative"}}><div style={{width:`${pct}%`,height:"100%",background:`linear-gradient(90deg,${t.color},${t.color}99)`,borderRadius:6}}/><div style={{position:"absolute",top:0,left:0,right:0,bottom:0,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 10px",fontSize:11,fontWeight:600}}><span>DB: €{t.cb.toFixed(2)}</span><span style={{color:"#9CA3AF"}}>Kosten: €{t.voiceCost.toFixed(2)}</span></div></div><div style={{width:50,fontSize:12,fontWeight:700,color:"#10B981",textAlign:"right"}}>{pct.toFixed(0)}%</div></div>);})}</div></div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:12}}>TOP-UP ECONOMICS</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[{a:5,m:5,s:0.33},{a:10,m:10,s:0.40},{a:20,m:20,s:0.55}].map((t,i)=>(<div key={i} style={{background:"#0F1117",borderRadius:10,padding:16,textAlign:"center"}}><div style={{fontSize:20,fontWeight:700,color:"#F9FAFB"}}>€{t.a}</div><div style={{fontSize:11,color:"#6B7280",margin:"4px 0"}}>~{t.m} Min · Stripe: €{t.s.toFixed(2)}</div><div style={{fontSize:13,fontWeight:700,color:"#10B981",marginTop:6}}>Marge: {(((t.a-t.s-t.m*0.06)/t.a)*100).toFixed(0)}%</div></div>))}</div></div>
</div>)}
{activeTab==="finance"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>SZENARIO-VERGLEICH — UMSATZ</div><div style={{display:"flex",alignItems:"flex-end",gap:16,height:200,padding:"0 8px"}}>{[0,1,2,3,4].map(yi=>{const mx=SCENARIOS.strong.years[4].revenue;return(<div key={yi} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><div style={{display:"flex",gap:3,alignItems:"flex-end",width:"100%",justifyContent:"center",height:170}}>{Object.entries(SCENARIOS).map(([k,v])=>{const h=(v.years[yi].revenue/mx)*160;return<div key={k} style={{width:18,height:Math.max(2,h),background:v.color,borderRadius:"4px 4px 1px 1px",opacity:0.85}}/>;})}</div><span style={{fontSize:11,color:"#6B7280"}}>J{yi+1}</span></div>);})}</div><div style={{display:"flex",justifyContent:"center",gap:20,marginTop:12}}>{Object.entries(SCENARIOS).map(([k,v])=>(<div key={k} style={{display:"flex",alignItems:"center",gap:6,fontSize:11,color:"#9CA3AF"}}><div style={{width:10,height:10,borderRadius:2,background:v.color}}/>{v.label}</div>))}</div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[{l:"Break-Even",s:[{s:"Vorsichtig",v:"~J1 (knapp)"},{s:"Realistisch",v:"J1 (solide)"},{s:"Stark",v:"J1"}]},{l:"€100k Gewinn/J",s:[{s:"Vorsichtig",v:"~J4"},{s:"Realistisch",v:"~J2"},{s:"Stark",v:"J1"}]},{l:"€1M+ Umsatz/J",s:[{s:"Vorsichtig",v:"nie (5J)"},{s:"Realistisch",v:"~J5"},{s:"Stark",v:"~J3"}]}].map((m,i)=>(<div key={i} style={{background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37"}}><div style={{fontSize:11,fontWeight:600,color:"#A855F7",marginBottom:10,textTransform:"uppercase"}}>{m.l}</div>{m.s.map((s,j)=>(<div key={j} style={{display:"flex",justifyContent:"space-between",fontSize:12,padding:"4px 0",color:"#D1D5DB"}}><span style={{color:"#9CA3AF"}}>{s.s}:</span><span style={{fontWeight:600,fontFamily:"'JetBrains Mono',monospace"}}>{s.v}</span></div>))}</div>))}</div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:12}}>TIER-MIX IMPACT</div><div style={{fontSize:13,color:"#D1D5DB",lineHeight:1.7}}><strong style={{color:"#F9FAFB"}}>Nicht der Einstiegsplan macht das Geschäft attraktiv — der Mix macht es.</strong> Shift von 5% auf 18% Partner erhöht ARPU um 42% bei identischer Marge.</div></div>
</div>)}
{activeTab==="architecture"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>SOPHIE 4-LAYER ARCHITEKTUR</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{ARCH_LAYERS.map((l,i)=>(<div key={i} onClick={()=>setExpandedLayer(expandedLayer===i?null:i)} style={{cursor:"pointer",background:expandedLayer===i?`${l.color}15`:"#0F1117",borderRadius:10,padding:"14px 16px",border:`1px solid ${expandedLayer===i?l.color:"#2A2D37"}`}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:8,background:`${l.color}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:l.color}}>{i+1}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:"#F9FAFB"}}>{l.name}</div><div style={{fontSize:11,color:"#9CA3AF"}}>{l.desc}</div></div><span style={{color:"#6B7280",fontSize:12}}>{expandedLayer===i?"▲":"▼"}</span></div>{expandedLayer===i&&<div style={{marginTop:10,paddingTop:10,borderTop:`1px solid ${l.color}30`,fontSize:12,color:"#D1D5DB",lineHeight:1.6}}>{l.details}</div>}</div>))}</div></div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:12}}>TECH STACK</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[{cat:"Frontend",items:["Vanilla HTML/JS","Vercel Hosting","PWA-fähig"],v:"Lean & schnell",c:"#3B82F6"},{cat:"Backend",items:["Vercel Serverless","Node.js / Stripe SDK","OpenAI Realtime API"],v:"Pay-per-use",c:"#10B981"},{cat:"Daten/Auth",items:["Supabase (Postgres+Auth)","RLS Policies","Magic Link"],v:"Kostenlos bis ~50k MAU",c:"#A855F7"}].map((s,i)=>(<div key={i} style={{background:"#0F1117",borderRadius:10,padding:16}}><div style={{fontSize:11,fontWeight:600,color:s.c,marginBottom:8,textTransform:"uppercase"}}>{s.cat}</div>{s.items.map((it,j)=><div key={j} style={{fontSize:12,color:"#D1D5DB",padding:"3px 0"}}>• {it}</div>)}<div style={{marginTop:8,fontSize:11,fontWeight:600,color:"#9CA3AF",borderTop:"1px solid #2A2D37",paddingTop:8}}>{s.v}</div></div>))}</div></div>
</div>)}
{activeTab==="project"&&(<div style={{display:"flex",flexDirection:"column",gap:16}}>
<div style={{fontSize:13,color:"#9CA3AF",background:"#1A1D27",borderRadius:12,padding:16,border:"1px solid #2A2D37"}}><strong style={{color:"#F9FAFB"}}>Umsetzung mit Claude (Max Plan)</strong> — 16 Wochen bis Go-to-Market.</div>
<div style={{background:"#1A1D27",borderRadius:12,padding:20,border:"1px solid #2A2D37"}}><div style={{fontSize:12,fontWeight:600,color:"#9CA3AF",marginBottom:16}}>SPRINT-ÜBERSICHT</div><div style={{display:"flex",flexDirection:"column"}}><div style={{display:"grid",gridTemplateColumns:"180px 1fr",gap:12,marginBottom:8}}><div/><div style={{display:"grid",gridTemplateColumns:"repeat(16,1fr)",gap:1}}>{Array.from({length:16},(_,i)=><div key={i} style={{fontSize:9,color:"#4B5563",textAlign:"center"}}>W{i+1}</div>)}</div></div>{SPRINTS.map((sp,i)=>{const sw=parseInt(sp.weeks.split("-")[0].replace("W",""))-1;const ew=parseInt(sp.weeks.split("-")[1].replace("W",""));return(<div key={i} style={{display:"grid",gridTemplateColumns:"180px 1fr",gap:12,marginBottom:4,cursor:"pointer"}} onClick={()=>setExpandedSprint(expandedSprint===i?null:i)}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:10,fontWeight:700,color:sp.color,background:`${sp.color}20`,padding:"2px 6px",borderRadius:4}}>{sp.prio}</span><span style={{fontSize:12,fontWeight:600,color:"#D1D5DB"}}>{sp.name}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(16,1fr)",gap:1,alignItems:"center"}}>{Array.from({length:16},(_,wi)=>(<div key={wi} style={{height:24,background:wi>=sw&&wi<ew?sp.color:"#1F2233",borderRadius:wi===sw?"4px 0 0 4px":wi===ew-1?"0 4px 4px 0":0,opacity:wi>=sw&&wi<ew?0.8:0.3}}/>))}</div></div>);})}</div><div style={{fontSize:11,color:"#F59E0B",marginTop:8}}>▎ Heute: Ende W3</div></div>
{SPRINTS.map((sp,i)=>(<div key={i} onClick={()=>setExpandedSprint(expandedSprint===i?null:i)} style={{background:"#1A1D27",borderRadius:12,padding:16,border:expandedSprint===i?`2px solid ${sp.color}`:"1px solid #2A2D37",cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:32,height:32,borderRadius:8,background:`${sp.color}25`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:sp.color}}>{sp.id}</div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:14,fontWeight:600,color:"#F9FAFB"}}>Sprint {sp.id}: {sp.name}</span><span style={{fontSize:10,fontWeight:600,color:sp.color,background:`${sp.color}20`,padding:"2px 8px",borderRadius:10}}>{sp.prio}</span>{sp.progress>0&&<span style={{fontSize:10,color:"#9CA3AF"}}>{sp.progress}%</span>}</div><div style={{fontSize:11,color:"#6B7280"}}>{sp.weeks} · Dep: {sp.deps}</div></div><span style={{color:"#6B7280",fontSize:12}}>{expandedSprint===i?"▲":"▼"}</span></div>{sp.progress>0&&<div style={{marginTop:8}}><ProgressBar progress={sp.progress} color={sp.color}/></div>}{expandedSprint===i&&(<div style={{marginTop:12,paddingTop:12,borderTop:"1px solid #2A2D37"}}><div style={{fontSize:11,fontWeight:600,color:"#9CA3AF",marginBottom:8}}>ARBEITSPAKETE</div>{sp.packages.map((p,j)=><div key={j} style={{fontSize:12,color:"#D1D5DB",padding:"4px 8px",background:"#0F111788",borderRadius:6,marginBottom:4}}>→ {p}</div>)}{sp.notes&&<div style={{marginTop:8,fontSize:11,color:"#6B7280",fontStyle:"italic"}}>{sp.notes}</div>}<div style={{marginTop:10,fontSize:11,color:sp.doneReached?"#10B981":"#F59E0B"}}><strong>Done:</strong> {sp.done} — {sp.doneReached?"✓":"Offen"}</div></div>)}</div>))}
</div>)}
{activeTab==="why"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
<div style={{background:"linear-gradient(135deg,#1A1D27,#1E1530)",borderRadius:14,padding:24,border:"1px solid #A855F740"}}><div style={{fontSize:11,fontWeight:600,color:"#A855F7",letterSpacing:"0.1em",textTransform:"uppercase",marginBottom:12}}>Warum Kunden es lieben</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>{[{t:"Sprechen statt Tippen",d:"Voice-first fühlt sich natürlicher und intimer an."},{t:"Eine Person, nicht ein Tool",d:"Stabiler Charakter — keine Modi-Auswahl."},{t:"Kontinuität erzeugt Bindung",d:"Sophie erinnert sich. Wie eine Vertraute."},{t:"Klarheit nach jedem Gespräch",d:"Session Insights, Key Takeaways, Action Plans."},{t:"Kein Urteil, kein Zeitdruck",d:"Immer da, immer aufmerksam."},{t:"Premium = mehr Tiefe",d:"Sophie kennt dich besser, reagiert feiner."}].map((c,i)=>(<div key={i} style={{background:"#0F111766",borderRadius:10,padding:14}}><div style={{fontSize:13,fontWeight:600,color:"#F9FAFB",marginBottom:4}}>{c.t}</div><div style={{fontSize:12,color:"#9CA3AF",lineHeight:1.5}}>{c.d}</div></div>))}</div></div>
<div style={{background:"linear-gradient(135deg,#1A1D27,#0F2218)",borderRadius:14,padding:24,border:"1px solid #10B98140"}}><div style={{fontSize:11,fontWeight:600,color:"#10B981",letterSpacing:"0.1em",textTransform:"uppercase",marginBottom:12}}>Warum wir Geld verdienen</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[{m:"72%",l:"DB-Marge",s:"stabil"},{m:"€25+",l:"ARPU/Mo",s:"steigt mit Mix"},{m:"€0",l:"Server-Fix",s:"Serverless"},{m:"~90%",l:"Top-up Marge",s:"€20 Paket"},{m:"4:1",l:"Revenue/Fix J3",s:"gesund"},{m:"∞",l:"Emotional Lock-in",s:"kein Vergleich"}].map((m,i)=>(<div key={i} style={{textAlign:"center",padding:12}}><div style={{fontSize:22,fontWeight:700,color:"#10B981"}}>{m.m}</div><div style={{fontSize:12,fontWeight:600,color:"#F9FAFB",marginTop:4}}>{m.l}</div><div style={{fontSize:11,color:"#6B7280"}}>{m.s}</div></div>))}</div></div>
<div style={{background:"linear-gradient(135deg,#1A1D27,#1A1830)",borderRadius:14,padding:24,border:"1px solid #6366F140"}}><div style={{fontSize:11,fontWeight:600,color:"#6366F1",letterSpacing:"0.1em",textTransform:"uppercase",marginBottom:12}}>Zukunftsmodell</div><div style={{display:"flex",flexDirection:"column",gap:12}}>{[{t:"AI Voice wird billiger",d:"Marge steigt automatisch. Prompt Caching senkt Kosten."},{t:"Relationship AI ist die nächste Kategorie",d:"Denkpartner, nicht Ersatzpartner."},{t:"Voice-first = Moat",d:"Switching-Kosten sind emotional, nicht technisch."},{t:"Subscription + Lock-in",d:"Retention basiert auf Beziehung, nicht Features."},{t:"Skalierbar ohne Team",d:"Serverless + Supabase + OpenAI = keine Ops."}].map((c,i)=>(<div key={i} style={{display:"flex",gap:14,padding:"10px 0",borderBottom:i<4?"1px solid #2A2D37":"none"}}><div style={{width:28,height:28,borderRadius:6,background:"#6366F125",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,color:"#6366F1",flexShrink:0}}>{i+1}</div><div><div style={{fontSize:13,fontWeight:600,color:"#F9FAFB"}}>{c.t}</div><div style={{fontSize:12,color:"#9CA3AF",lineHeight:1.5,marginTop:2}}>{c.d}</div></div></div>))}</div></div>
<div style={{background:"#1A1D27",borderRadius:14,padding:24,border:"1px solid #2A2D37",textAlign:"center"}}><div style={{fontSize:18,fontWeight:700,color:"#F9FAFB",marginBottom:12}}>Ehrliches Gesamturteil</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:16}}>{[{y:"Jahr 1",v:"Fragil, aber tragfähig",c:"#F59E0B"},{y:"Jahr 3",v:"Gutes Geschäft",c:"#3B82F6"},{y:"Jahr 5",v:"Sehr attraktiv",c:"#10B981"}].map((m,i)=>(<div key={i} style={{padding:12,background:`${m.c}15`,borderRadius:10,border:`1px solid ${m.c}30`}}><div style={{fontSize:14,fontWeight:700,color:m.c}}>{m.y}</div><div style={{fontSize:12,color:"#D1D5DB",marginTop:4}}>{m.v}</div></div>))}</div><div style={{fontSize:14,color:"#A855F7",fontWeight:600,fontStyle:"italic"}}>Die wichtigste Zahl: Wie viele zahlende Nutzer werden mit der Zeit profitabler?</div></div>
</div>)}
</div>
</div>
  );
}
